# Site
name: "Blakadder's Smarthome Shenanigans"
title: "BSS"
description: "Blakadder's explorations in DIY smart home"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
google_analytics: 'UA-140681905-4'
disqus: 'blakadder'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: arguson@gmail.com

# Authors
authors:
  blak:
    name: blakadder
    display_name: blakadder
    avatar: 'assets/images/avatar.png'
    email: arguson@gmail.com
    twitter: https://twitter.com/blakadder_
    description: "Chief shenaniganeer!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
